/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lv_edi_EDI_3DAtA_opencvcudainterface_Compute */

#ifndef _Included_lv_edi_EDI_3DAtA_opencvcudainterface_Compute
#define _Included_lv_edi_EDI_3DAtA_opencvcudainterface_Compute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lv_edi_EDI_3DAtA_opencvcudainterface_Compute
 * Method:    gaussianBlur
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_lv_edi_EDI_13DAtA_opencvcudainterface_Compute_gaussianBlur
  (JNIEnv * env, jobject obj, jdoubleArray input, jint rows, jint cols);

#ifdef __cplusplus
}
#endif
#endif
