/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lv_edi_EDI_3DAtA_opencvcudainterface_Compute */

#ifndef _Included_lv_edi_EDI_3DAtA_opencvcudainterface_Compute
#define _Included_lv_edi_EDI_3DAtA_opencvcudainterface_Compute

extern "C" {

/*
 * Class:     lv_edi_EDI_3DAtA_opencvcudainterface_Compute
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lv_edi_EDI_13DAtA_opencvcudainterface_Compute_test
  (JNIEnv *, jobject);


}
#endif
#endif
